export const cookieOptions = {
  maxAge: process.env.ACCESS_TOKEN_LIFE_SECONDS,
  httpOnly: true,
};

export const SocketEventDefault = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  ERROR: "error",
};

export const SocketEvent = {
  // emit
  EMIT_LOAD_CHANNELS: "EMIT_LOAD_CHANNELS",
  EMIT_ADD_CHANNEL: "EMIT_ADD_CHANNEL",
  EMIT_ADD_USERS_TO_CHANNEL: "EMIT_ADD_USERS_TO_CHANNEL",
  EMIT_USER_LEAVE_CHANNEL: "EMIT_USER_LEAVE_CHANNEL",
  EMIT_EDIT_CHANNEL_NAME: "EMIT_EDIT_CHANNEL_NAME",
  EMIT_EDIT_CHANNEL_OPTIONAL_FIELDS: "EMIT_EDIT_CHANNEL_OPTIONAL_FIELDS",
  EMIT_CHANGE_TO_PRIVATE_CHANNEL: "EMIT_CHANGE_TO_PRIVATE_CHANNEL",

  EMIT_LOAD_MESSAGES: "EMIT_LOAD_MESSAGES",
  EMIT_LOAD_MORE_MESSAGES: "EMIT_LOAD_MORE_MESSAGES",
  EMIT_ADD_MESSAGE: "EMIT_ADD_MESSAGE",
  EMIT_SHARE_MESSAGE_TO_CHANNEL: "EMIT_SHARE_MESSAGE_TO_CHANNEL",
  EMIT_SHARE_MESSAGE_TO_GROUP_USERS: "EMIT_SHARE_MESSAGE_TO_GROUP_USERS",
  EMIT_EDIT_MESSAGE: "EMIT_EDIT_MESSAGE",
  EMIT_REMOVE_MESSAGE: "EMIT_REMOVE_MESSAGE",
  EMIT_STARRED_MESSAGE: "EMIT_STARRED_MESSAGE",
  EMIT_REACTION_MESSAGE: "EMIT_REACTION_MESSAGE",
  EMIT_REMOVE_MESSAGE_FILE: "EMIT_REMOVE_MESSAGE_FILE",

  // on
  ON_USER_ONLINE: "ON_USER_ONLINE",
  ON_USER_OFFLINE: "ON_USER_OFFLINE",
  ON_CHANNELS: "ON_CHANNELS",
  ON_ADDED_CHANNEL: "ON_ADDED_CHANNEL",
  ON_REMOVED_CHANNEL: "ON_REMOVED_CHANNEL",
  ON_EDITED_CHANNEL: "ON_EDITED_CHANNEL",
  ON_EDITED_CHANNEL_USERS: "ON_EDITED_CHANNEL_USERS",
  ON_EDITED_CHANNEL_UPDATED_TIME: "ON_EDITED_CHANNEL_UPDATED_TIME",
  ON_EDITED_CHANNEL_UNREAD_MESSAGE_COUNT: "ON_EDITED_CHANNEL_UNREAD_MESSAGE_COUNT",

  ON_MESSAGES: "ON_MESSAGES",
  ON_MORE_MESSAGES: "ON_MORE_MESSAGES",
  ON_ADDED_MESSAGE: "ON_ADDED_MESSAGE",
  ON_EDITED_MESSAGE: "ON_EDITED_MESSAGE",
  ON_REMOVED_MESSAGE: "ON_REMOVED_MESSAGE",
  ON_REMOVED_MESSAGE_FILE: "ON_REMOVED_MESSAGE_FILE",
  ON_SHARE_MESSAGE_TO_CHANNEL: "ON_SHARE_MESSAGE_TO_CHANNEL",

  ON_AUTHENTICATED: "ON_AUTHENTICATED",
  ON_ATOKEN_EXPIRED: "ON_ATOKEN_EXPIRED",
};
